import bcrypt from 'bcryptjs';
import { School } from './models/School.js';
import { SchoolUser } from './models/SchoolUser.js';

const DEFAULT_TEACHERS = [
  {
    employeeId: 'TCH-001',
    firstName: 'Rajesh',
    lastName: 'Kumar',
    role: 'TEACHER',
    employeeType: 'TEACHER',
    phone: '+91 98765 43210',
    email: 'rajesh.kumar@greenfield.edu',
    gender: 'MALE',
    designation: 'Senior Teacher',
    specialization: 'Physics & Mathematics',
    qualification: 'M.Sc. Physics, B.Ed',
    department: 'Academic & Faculty',
    joiningDate: new Date('2018-06-15'),
    dateOfBirth: new Date('1985-03-22'),
    bloodGroup: 'O+',
    experience: 6,
    basicSalary: 52000,
    address: {
      addressLine: '45-A Sector 45',
      city: 'Noida',
      state: 'Uttar Pradesh',
      pincode: '201301',
    },
    bankDetails: {
      accountName: 'Rajesh Kumar',
      accountNumber: '1234567890123456',
      ifscCode: 'HDFC0001234',
      bankName: 'HDFC Bank',
      branchName: 'Noida Main',
      accountType: 'SALARY',
    },
    status: 'ACTIVE',
    emailPrefix: 'rajesh.kumar',
  },
  {
    employeeId: 'TCH-002',
    firstName: 'Priya',
    lastName: 'Sharma',
    role: 'TEACHER',
    employeeType: 'TEACHER',
    phone: '+91 99876 54321',
    email: 'priya.sharma@greenfield.edu',
    gender: 'FEMALE',
    designation: 'Senior Teacher',
    specialization: 'English Literature & Language',
    qualification: 'M.A. English, B.Ed',
    department: 'Academic & Faculty',
    joiningDate: new Date('2019-07-01'),
    dateOfBirth: new Date('1990-05-18'),
    bloodGroup: 'A+',
    experience: 5,
    basicSalary: 50000,
    address: {
      addressLine: '127 Sector 32',
      city: 'Noida',
      state: 'Uttar Pradesh',
      pincode: '201304',
    },
    bankDetails: {
      accountName: 'Priya Sharma',
      accountNumber: '9876543210987654',
      ifscCode: 'ICIC0000456',
      bankName: 'ICICI Bank',
      branchName: 'Sector 62',
      accountType: 'SALARY',
    },
    status: 'ACTIVE',
    emailPrefix: 'priya.sharma',
  },
  {
    employeeId: 'TCH-003',
    firstName: 'Vikram',
    lastName: 'Singh',
    role: 'TEACHER',
    employeeType: 'TEACHER',
    phone: '+91 97654 32109',
    email: 'vikram.singh@greenfield.edu',
    gender: 'MALE',
    designation: 'Assistant Teacher',
    specialization: 'Chemistry & Environmental Science',
    qualification: 'M.Sc. Chemistry, B.Ed',
    department: 'Academic & Faculty',
    joiningDate: new Date('2021-08-10'),
    dateOfBirth: new Date('1992-09-14'),
    bloodGroup: 'B+',
    experience: 3,
    basicSalary: 38000,
    address: {
      addressLine: '89 Sector 18',
      city: 'Noida',
      state: 'Uttar Pradesh',
      pincode: '201301',
    },
    bankDetails: {
      accountName: 'Vikram Singh',
      accountNumber: '5555666677778888',
      ifscCode: 'SBIN0003456',
      bankName: 'State Bank of India',
      branchName: 'Sector 18 Branch',
      accountType: 'SALARY',
    },
    status: 'ACTIVE',
    emailPrefix: 'vikram.singh',
  },
  {
    employeeId: 'TCH-004',
    firstName: 'Anjali',
    lastName: 'Desai',
    role: 'TEACHER',
    employeeType: 'TEACHER',
    phone: '+91 96543 21098',
    email: 'anjali.desai@greenfield.edu',
    gender: 'FEMALE',
    designation: 'Assistant Teacher',
    specialization: 'Social Studies & History',
    qualification: 'M.A. History, B.Ed',
    department: 'Academic & Faculty',
    joiningDate: new Date('2022-06-01'),
    dateOfBirth: new Date('1994-12-25'),
    bloodGroup: 'O-',
    experience: 2,
    basicSalary: 36000,
    address: {
      addressLine: '234 Sector 25',
      city: 'Noida',
      state: 'Uttar Pradesh',
      pincode: '201301',
    },
    bankDetails: {
      accountName: 'Anjali Desai',
      accountNumber: '3333444455556666',
      ifscCode: 'HDFC0002567',
      bankName: 'HDFC Bank',
      branchName: 'Sector 32',
      accountType: 'SALARY',
    },
    status: 'ACTIVE',
    emailPrefix: 'anjali.desai',
  },
  {
    employeeId: 'TCH-005',
    firstName: 'Arjun',
    lastName: 'Patel',
    role: 'TEACHER',
    employeeType: 'TEACHER',
    phone: '+91 95432 10987',
    email: 'arjun.patel@greenfield.edu',
    gender: 'MALE',
    designation: 'Senior Teacher',
    specialization: 'Computer Science & IT',
    qualification: 'M.Tech IT, B.Ed',
    department: 'Academic & Faculty',
    joiningDate: new Date('2017-04-15'),
    dateOfBirth: new Date('1988-07-20'),
    bloodGroup: 'AB+',
    experience: 7,
    basicSalary: 58000,
    address: {
      addressLine: '567 Sector 51',
      city: 'Noida',
      state: 'Uttar Pradesh',
      pincode: '201305',
    },
    bankDetails: {
      accountName: 'Arjun Patel',
      accountNumber: '7777888899990000',
      ifscCode: 'PUNB0002345',
      bankName: 'Punjab National Bank',
      branchName: 'City Center',
      accountType: 'SALARY',
    },
    status: 'ACTIVE',
    emailPrefix: 'arjun.patel',
  },
  {
    employeeId: 'TCH-006',
    firstName: 'Meera',
    lastName: 'Gupta',
    role: 'TEACHER',
    employeeType: 'TEACHER',
    phone: '+91 94321 09876',
    email: 'meera.gupta@greenfield.edu',
    gender: 'FEMALE',
    designation: 'Head of Faculty',
    specialization: 'Biology & Life Sciences',
    qualification: 'M.Sc. Biology, B.Ed, NET',
    department: 'Academic & Faculty',
    joiningDate: new Date('2016-08-01'),
    dateOfBirth: new Date('1987-02-10'),
    bloodGroup: 'A-',
    experience: 8,
    basicSalary: 65000,
    address: {
      addressLine: '901 Sector 75',
      city: 'Noida',
      state: 'Uttar Pradesh',
      pincode: '201307',
    },
    bankDetails: {
      accountName: 'Meera Gupta',
      accountNumber: '2222333344445555',
      ifscCode: 'ICIC0001789',
      bankName: 'ICICI Bank',
      branchName: 'Electronic City',
      accountType: 'SALARY',
    },
    status: 'ACTIVE',
    emailPrefix: 'meera.gupta',
  },
  {
    employeeId: 'TCH-007',
    firstName: 'Sameer',
    lastName: 'Khan',
    role: 'TEACHER',
    employeeType: 'TEACHER',
    phone: '+91 93210 98765',
    email: 'sameer.khan@greenfield.edu',
    gender: 'MALE',
    designation: 'Assistant Teacher',
    specialization: 'Physical Education & Sports',
    qualification: 'B.P.Ed, B.Ed',
    department: 'Academic & Faculty',
    joiningDate: new Date('2022-09-01'),
    dateOfBirth: new Date('1995-11-08'),
    bloodGroup: 'B-',
    experience: 1,
    basicSalary: 32000,
    address: {
      addressLine: '111 Sector 22',
      city: 'Noida',
      state: 'Uttar Pradesh',
      pincode: '201301',
    },
    bankDetails: {
      accountName: 'Sameer Khan',
      accountNumber: '8888999900001111',
      ifscCode: 'SBIN0005678',
      bankName: 'State Bank of India',
      branchName: 'Noida City Center',
      accountType: 'SALARY',
    },
    status: 'ACTIVE',
    emailPrefix: 'sameer.khan',
  },
  {
    employeeId: 'TCH-008',
    firstName: 'Divya',
    lastName: 'Nair',
    role: 'TEACHER',
    employeeType: 'TEACHER',
    phone: '+91 92109 87654',
    email: 'divya.nair@greenfield.edu',
    gender: 'FEMALE',
    designation: 'Senior Teacher',
    specialization: 'Mathematics & Statistics',
    qualification: 'M.Sc. Math, B.Ed, IGNOU',
    department: 'Academic & Faculty',
    joiningDate: new Date('2020-05-10'),
    dateOfBirth: new Date('1989-06-30'),
    bloodGroup: 'AB-',
    experience: 4,
    basicSalary: 48000,
    address: {
      addressLine: '345 Sector 37',
      city: 'Noida',
      state: 'Uttar Pradesh',
      pincode: '201303',
    },
    bankDetails: {
      accountName: 'Divya Nair',
      accountNumber: '4444555566667777',
      ifscCode: 'HDFC0003890',
      bankName: 'HDFC Bank',
      branchName: 'Sector 62',
      accountType: 'SALARY',
    },
    status: 'ACTIVE',
    emailPrefix: 'divya.nair',
  },
];

export async function seedTeachers() {
  const schools = await School.find({}).select('_id name contact');
  const defaultPasswordHash = await bcrypt.hash('Password@123', 10);
  let totalSeeded = 0;

  for (const school of schools) {
    const domain = school.contact?.email ? school.contact.email.split('@')[1] : 'school.edu';

    for (const teacher of DEFAULT_TEACHERS) {
      const email = `${teacher.emailPrefix}@${domain}`.toLowerCase();
      const existingTeacher = await SchoolUser.findOne({
        schoolId: school._id,
        $or: [{ email }, { employeeId: teacher.employeeId }],
      });

      if (!existingTeacher) {
        await SchoolUser.create({
          schoolId: school._id,
          employeeId: teacher.employeeId,
          firstName: teacher.firstName,
          lastName: teacher.lastName,
          name: `${teacher.firstName} ${teacher.lastName}`.trim(),
          email,
          passwordHash: defaultPasswordHash,
          role: 'TEACHER',
          employeeType: 'TEACHER',
          phone: teacher.phone,
          gender: teacher.gender,
          designation: teacher.designation,
          specialization: teacher.specialization,
          qualification: teacher.qualification,
          department: teacher.department,
          joiningDate: teacher.joiningDate,
          dateOfBirth: teacher.dateOfBirth,
          bloodGroup: teacher.bloodGroup,
          experience: teacher.experience,
          basicSalary: teacher.basicSalary,
          address: teacher.address,
          bankDetails: teacher.bankDetails,
          documents: [],
          photo: '',
          status: teacher.status,
        });
        totalSeeded++;
      }
    }
  }

  if (totalSeeded > 0) {
    console.log(`✓ Teachers seeded: ${totalSeeded} faculty members (8 teachers with complete profiles)`);
  }
  return totalSeeded;
}

export default seedTeachers;
