/**
 * Stable, machine-readable error codes for the Parent APK API.
 * Land in the JSON body as `code`. Public contract for the Flutter client —
 * add new ones, never repurpose. Mirrors teacher/student error-code files.
 */
export const PARENT_ERR = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',

  PARENT_NOT_FOUND: 'PARENT_NOT_FOUND',
  PARENT_INACTIVE: 'PARENT_INACTIVE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
  CURRENT_PASSWORD_INVALID: 'CURRENT_PASSWORD_INVALID',
  ACCOUNT_NOT_PROVISIONED: 'ACCOUNT_NOT_PROVISIONED',

  NO_LINKED_CHILDREN: 'NO_LINKED_CHILDREN',
  CHILD_ACCESS_DENIED: 'CHILD_ACCESS_DENIED',
  CHILD_NOT_FOUND: 'CHILD_NOT_FOUND',
  RESOURCE_FORBIDDEN: 'RESOURCE_FORBIDDEN',
  NO_ACTIVE_ENROLLMENT: 'NO_ACTIVE_ENROLLMENT',
  RESULT_NOT_PUBLISHED: 'RESULT_NOT_PUBLISHED',

  PAYMENTS_NOT_CONFIGURED: 'PAYMENTS_NOT_CONFIGURED',
  INVOICE_NOT_PAYABLE: 'INVOICE_NOT_PAYABLE',
  INVOICE_ALREADY_PAID: 'INVOICE_ALREADY_PAID',
  PAYMENT_AMOUNT_INVALID: 'PAYMENT_AMOUNT_INVALID',
  PAYMENT_SIGNATURE_INVALID: 'PAYMENT_SIGNATURE_INVALID',
  PAYMENT_GATEWAY_ERROR: 'PAYMENT_GATEWAY_ERROR',
  DUPLICATE_REQUEST: 'DUPLICATE_REQUEST',

  DOCUMENT_PATH_INVALID: 'DOCUMENT_PATH_INVALID',
};
