/**
 * Stable, machine-readable error codes for the Student APK API.
 *
 * These land in the JSON body as `code` (errorHandler.js surfaces `err.code`).
 * The Flutter client keys UI behaviour off these strings, so treat them as a
 * public contract — add new ones, never repurpose an existing one.
 *
 * Mirrors src/constants/teacherErrorCodes.js.
 */
export const STUDENT_ERR = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',

  STUDENT_NOT_FOUND: 'STUDENT_NOT_FOUND',
  STUDENT_INACTIVE: 'STUDENT_INACTIVE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
  CURRENT_PASSWORD_INVALID: 'CURRENT_PASSWORD_INVALID',
  ACCOUNT_NOT_PROVISIONED: 'ACCOUNT_NOT_PROVISIONED',

  SCHOOL_ACCESS_DENIED: 'SCHOOL_ACCESS_DENIED',
  CLASS_ACCESS_DENIED: 'CLASS_ACCESS_DENIED',
  SECTION_ACCESS_DENIED: 'SECTION_ACCESS_DENIED',
  RESOURCE_FORBIDDEN: 'RESOURCE_FORBIDDEN',
  NO_ACTIVE_YEAR: 'NO_ACTIVE_YEAR',
  NO_ACTIVE_ENROLLMENT: 'NO_ACTIVE_ENROLLMENT',

  RESULT_NOT_PUBLISHED: 'RESULT_NOT_PUBLISHED',
  HOMEWORK_NOT_SUBMITTABLE: 'HOMEWORK_NOT_SUBMITTABLE',
  ALREADY_SUBMITTED: 'ALREADY_SUBMITTED',
  SUBMISSION_WINDOW_CLOSED: 'SUBMISSION_WINDOW_CLOSED',
  DUPLICATE_REQUEST: 'DUPLICATE_REQUEST',
  UPLOAD_REJECTED: 'UPLOAD_REJECTED',
  LEAVE_NOT_CANCELLABLE: 'LEAVE_NOT_CANCELLABLE',
  LEAVE_NOT_EDITABLE: 'LEAVE_NOT_EDITABLE',
  LEAVE_OVERLAP: 'LEAVE_OVERLAP',
  DOCUMENT_PATH_INVALID: 'DOCUMENT_PATH_INVALID',
};
