/**
 * Stable, machine-readable error codes for the Teacher APK API.
 *
 * These land in the JSON body as `code` (errorHandler.js surfaces `err.code`).
 * The Flutter client keys UI behaviour off these strings, so treat them as a
 * public contract — add new ones, never repurpose an existing one.
 */
export const TEACHER_ERR = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',

  TEACHER_NOT_FOUND: 'TEACHER_NOT_FOUND',
  TEACHER_INACTIVE: 'TEACHER_INACTIVE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
  CURRENT_PASSWORD_INVALID: 'CURRENT_PASSWORD_INVALID',

  SCHOOL_ACCESS_DENIED: 'SCHOOL_ACCESS_DENIED',
  CLASS_ACCESS_DENIED: 'CLASS_ACCESS_DENIED',
  SECTION_ACCESS_DENIED: 'SECTION_ACCESS_DENIED',
  SUBJECT_ACCESS_DENIED: 'SUBJECT_ACCESS_DENIED',
  STUDENT_ACCESS_DENIED: 'STUDENT_ACCESS_DENIED',
  NOT_ASSIGNED: 'NOT_ASSIGNED',
  RESOURCE_FORBIDDEN: 'RESOURCE_FORBIDDEN',
  NO_ACTIVE_YEAR: 'NO_ACTIVE_YEAR',

  ATTENDANCE_ALREADY_SUBMITTED: 'ATTENDANCE_ALREADY_SUBMITTED',
  ATTENDANCE_FINALIZED: 'ATTENDANCE_FINALIZED',
  INVALID_ATTENDANCE_STATUS: 'INVALID_ATTENDANCE_STATUS',

  INVALID_MARKS: 'INVALID_MARKS',
  EXAM_FINALIZED: 'EXAM_FINALIZED',

  DUPLICATE_REQUEST: 'DUPLICATE_REQUEST',
  UPLOAD_REJECTED: 'UPLOAD_REJECTED',
  LEAVE_NOT_CANCELLABLE: 'LEAVE_NOT_CANCELLABLE',
  LEAVE_OVERLAP: 'LEAVE_OVERLAP',
};
