/**
 * Stable machine-readable error codes for the Transport module. errorHandler.js
 * surfaces `err.code` in the JSON body, so the frontend can branch on these
 * instead of matching on message text.
 */
export const TRANSPORT_ERR = {
  VALIDATION_ERROR: 'TRANSPORT_VALIDATION_ERROR',
  NOT_FOUND: 'TRANSPORT_NOT_FOUND',
  DUPLICATE: 'TRANSPORT_DUPLICATE',
  IN_USE: 'TRANSPORT_IN_USE',
  VEHICLE_INACTIVE: 'TRANSPORT_VEHICLE_INACTIVE',
  DRIVER_INACTIVE: 'TRANSPORT_DRIVER_INACTIVE',
  ALREADY_ASSIGNED: 'TRANSPORT_ALREADY_ASSIGNED',
  CAPACITY_FULL: 'TRANSPORT_CAPACITY_FULL',
  ROUTE_NOT_READY: 'TRANSPORT_ROUTE_NOT_READY',
  NOT_PICKED_UP: 'TRANSPORT_NOT_PICKED_UP',
  UNAUTHORIZED: 'TRANSPORT_UNAUTHORIZED',
  FORBIDDEN: 'TRANSPORT_FORBIDDEN',
  INVALID_CREDENTIALS: 'TRANSPORT_INVALID_CREDENTIALS',
};
