/**
 * Stable, machine-readable error codes for the Transport APK API.
 * Land in the JSON body as `code`. Public contract for the Flutter client.
 * Mirrors teacher/student/parent error-code files.
 */
export const TRANSPORT_ERR = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',

  STAFF_NOT_FOUND: 'STAFF_NOT_FOUND',
  STAFF_INACTIVE: 'STAFF_INACTIVE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
  CURRENT_PASSWORD_INVALID: 'CURRENT_PASSWORD_INVALID',
  TRANSPORT_ROLE_REQUIRED: 'TRANSPORT_ROLE_REQUIRED',

  TRIP_ACCESS_DENIED: 'TRIP_ACCESS_DENIED',
  VEHICLE_ACCESS_DENIED: 'VEHICLE_ACCESS_DENIED',
  ROUTE_ACCESS_DENIED: 'ROUTE_ACCESS_DENIED',
  NO_ASSIGNMENT: 'NO_ASSIGNMENT',

  INVALID_TRIP_TRANSITION: 'INVALID_TRIP_TRANSITION',
  TRIP_ALREADY_STARTED: 'TRIP_ALREADY_STARTED',
  TRIP_NOT_ACTIVE: 'TRIP_NOT_ACTIVE',
  TRIP_DATE_INVALID: 'TRIP_DATE_INVALID',
  DUPLICATE_TRIP: 'DUPLICATE_TRIP',
  VEHICLE_NOT_AVAILABLE: 'VEHICLE_NOT_AVAILABLE',
  INSPECTION_REQUIRED: 'INSPECTION_REQUIRED',
  INSPECTION_CRITICAL_FAILURE: 'INSPECTION_CRITICAL_FAILURE',

  STUDENT_NOT_ON_TRIP: 'STUDENT_NOT_ON_TRIP',
  ALREADY_BOARDED: 'ALREADY_BOARDED',
  NOT_BOARDED: 'NOT_BOARDED',
  BOARDING_STATE_CONFLICT: 'BOARDING_STATE_CONFLICT',

  GPS_INVALID_COORDS: 'GPS_INVALID_COORDS',
  GPS_STALE_TIMESTAMP: 'GPS_STALE_TIMESTAMP',
  GPS_DISABLED: 'GPS_DISABLED',

  SOS_ALREADY_ACTIVE: 'SOS_ALREADY_ACTIVE',
  SOS_STATE_CONFLICT: 'SOS_STATE_CONFLICT',
  ALERT_STATE_CONFLICT: 'ALERT_STATE_CONFLICT',

  DUPLICATE_REQUEST: 'DUPLICATE_REQUEST',
  UPLOAD_REJECTED: 'UPLOAD_REJECTED',
};
